name: ArchanaGowda
favicon: null
layout_spectrum: 0.98584
typography_spectrum: 0.7647234168834984
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#2a1e32'
    - '#5f251a'
    - '#913b2a'
    - '#a2503b'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
