name: ArchanaGowda
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7647234168834984
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#2a1e32'
    - '#5f251a'
    - '#913b2a'
    - '#a2503b'
  brandStrength: 1
  lightness: 0.34314064448699355
  saturation: 0.39897986338473856
  rhythmicContrast: 0.5029488164000213
purpose: []
